### ISSUE TITLE
Invalid parsing of credential id.

### ISSUE THREAD

**Issue by c128128** [duo-labs/webauthn.io#103]
Looks like [Credential ID](https://www.w3.org/TR/webauthn-2/#credential-id) is not parsed correctly. From `specs` it can be `At least 16 bytes that include at least 100 bits of entropy` but when we use a newly 16 bytes data (an UUID), we get this error (check image). But if `Credential ID` is a valid ASCII string that all is working as expected. 

![WebAuthn io](https://github.com/duo-labs/webauthn.io/assets/69604865/2129223e-42ab-42e7-8c16-744d409120db)

**Comment by MasterKale** [comment]
Hello @c128128, what's the response that gets sent back to `/registration/verification` after registration?

**Comment by c128128** [comment]
`AUTHENTICATION OPTIONS`

```JSON
{
  "challenge": "UWgQo34qUMGhspUuCGXz_aebiL0qmC70Fb11llGviYAIkx8XGmbuMRp52JPAmw9VBxK74JaJKkpHYWVosTAd8A",
  "timeout": 60000,
  "rpId": "webauthn.io",
  "allowCredentials": [
    {
      "id": "aE3nK_bxTbi8Q8oIjPTauA",
      "type": "public-key",
      "transports": [
        "internal",
        "hybrid"
      ]
    }
  ],
  "userVerification": "preferred"
}
```
`AUTHENTICATION RESPONSE`

```JSON
{
  "id": "aE3nK_bxTbi8Q8oIjPTauA",
  "rawId": "aE3nK_bxTbi8Q8oIjPTauA",
  "response": {
    "authenticatorData": "dKbqkhPJnC90siSSsyDPQCYqlMGpUKA5fyklC2CEHvAdAAAAAA",
    "clientDataJSON": "eyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoiVVdnUW8zNHFVTUdoc3BVdUNHWHpfYWViaUwwcW1DNzBGYjExbGxHdmlZQUlreDhYR21idU1ScDUySlBBbXc5VkJ4Szc0SmFKS2twSFlXVm9zVEFkOEEiLCJvcmlnaW4iOiJodHRwczovL3dlYmF1dGhuLmlvIn0",
    "signature": "MEYCIQDROvszXPDSu2tglRxNkheoUvlKcTrUvLXD4hAH4W8grgIhAJi6JBXAfnbvK-CsdTY_MhRh6fAbsHsS-Gw_g-D7rp2Y",
    "userHandle": "hM�+��M��C�\b��ڸ"
  },
  "type": "public-key",
  "clientExtensionResults": {},
  "authenticatorAttachment": "platform"
}
```

**Comment by MasterKale** [comment]
Hmm, what did you specify for `user.id` in your registration options?

**Comment by r4gus** [comment]
I had the same problem with the site. From the outside (and reading the error message) it looks like you expect only ASCII strings for id but the spec says that id is a "byte sequence" so values like `h'FF2E54C6EBFC07DC01473CD0D02C4B5588E034C85CF537F568A24A3BF2E91701'` should be allowed.
