### ISSUE TITLE
Please add Bitwarden aaguid

### ISSUE THREAD

**Issue by mimi89999** [duo-labs/webauthn.io#110]
It's https://github.com/bitwarden/clients/blob/master/libs/common/src/vault/services/fido2/fido2-authenticator.service.ts#L28

I see that it's already in https://github.com/passkeydeveloper/passkey-authenticator-aaguids/blob/main/aaguid.json#L68

**Comment by MasterKale** [comment]
webauthn.io has been updated to recognize Bitwarden's AAGUID:

![Screenshot 2024-01-04 at 11 23 12 AM](https://github.com/duo-labs/webauthn.io/assets/5166470/0b02b94e-7764-44d4-a688-b2e33e612507)

**Comment by mimi89999** [comment]
Thanks for adding it. It doesn't look that nice for me though.
![Screenshot 2024-01-04 at 20-38-54 A demonstration of the WebAuthn specification](https://github.com/duo-labs/webauthn.io/assets/8530546/70072792-a9d2-4e41-be97-d1592090e71f)

I would also like to ask about Bitwarden being shown as `device-bound credential of unknown discoverability` when Google Password managed is shown as `synced passkey`.

I asked about that on the Bitwarden forum, but didn't get any meaningful reply: https://community.bitwarden.com/t/bitwarden-passkeys-shown-as-device-bound-credential-of-unknown-discoverability/60097

**Comment by MasterKale** [comment]
@mimi89999 What browser are you viewing that in? Can you try refreshing your browser cache? I made some significant CSS changes in #118 and tested as best I could on macOS but maybe I missed something.

> I would also like to ask about Bitwarden being shown as device-bound credential of unknown discoverability when Google Password managed is shown as synced passkey.

The best way for Bitwarden credentials to display as discoverable is for Bitwarden to support the [`credProps` extension](https://www.w3.org/TR/webauthn-2/#sctn-authenticator-credential-properties-extension). webauthn.io looks to that first to understand if a credential is discoverable or not.

In lieu of that the site next tries to infer if it's discoverable or not based on registration options requiring discoverable credentials...


![Screenshot 2024-01-04 at 11 59 26 AM](https://github.com/duo-labs/webauthn.io/assets/5166470/91646174-b7f6-4ca7-a083-ee40cc92c565)

...but generally speaking it's much better for RP's to get the signal back via `credProps`.
