### ISSUE TITLE
Demo on webpage not shown - JS file could not be loaded

### ISSUE THREAD

**Issue by RobertRad** [duo-labs/webauthn.io#116]
Hi,

the Webpage shows no demo. 😮
In the console / network tab it is shown that https://webauthn.io/static/js/simplewebauthn-browser.8.2.1.umd.min.js could not be loaded.

**Comment by MasterKale** [comment]
Hello @RobertRad, thank you for your vigilance! I made some changes to the site yesterday and actually ran into disk space issues (🤦) that I managed to work past this morning. The site should now be back up and running!
