### ISSUE TITLE
Google chrome asking to allow or block request when attestation is "direct"

### ISSUE THREAD

**Issue by chrismccaw** [duo-labs/webauthn.io#12]
I am using Chrome and when selecting the attestation type to be "direct" an additional popup appears asking to "Allow" or "Block" my authenticator details. Even though I block the request I can still login. Is this expected?

<img width="488" alt="Screen Shot 2019-07-08 at 2 21 31 PM" src="https://user-images.githubusercontent.com/1656770/60843524-bde5f080-a18b-11e9-911f-08d87f87d4de.png">

**Comment by aseigler** [comment]
Yes, that is totally normal and expected. Chrome, for privacy purposes, offers you the option of not providing your authenticator make/model (aka AAGUID) to the server. The server has the option of not allowing the session if you choose not to provide this detail, but for this demo site purposes, the server does not care. In the real world, your mileage may vary. An enterprise or bank for example might insist on knowing you are using an authenticator from a trusted vendor.

**Comment by chrismccaw** [comment]
Ah I see. Yeh, I noticed firefox does not present this popup so Chrome is just been transparent about the data being sent.
