### ISSUE TITLE
Initial Registration fails the first time on MacOS Safari 17.3 and 16.6 but subsequent attempts work

### ISSUE THREAD

**Issue by jschlesser** [duo-labs/webauthn.io#121]
I'm leaving this here so anyone else digging doesn't go further..  It looks like it's related to a bug in webkit on macOS only (not iOS) and not due to this website or the SimpleWebAuthn library.   Some links are at the end in case you are interested.  It looks like the bug has been picked up by the webkit team.

When trying to process a new registration on the webauthn.io website using macOS Safari 17.3 and 16.6, the first time the register button is clicked an error message is displayed on the page: 'Operation failed.'  Note that this is with the default settings, nothing changed in advanced settings.

In the developer console the last message is: 'Conditional UI request was aborted'.
This happens when I have no pre-existing passkey registered as well as having one.

Details here:
https://github.com/MasterKale/SimpleWebAuthn/discussions/389
https://bugs.webkit.org/show_bug.cgi?id=257176
https://github.com/WebKit/WebKit/pull/22983

**Comment by jschlesser** [comment]
Looks like the bug is fixed and merged in webkit.   https://github.com/WebKit/WebKit/pull/22983
No telling how long till it makes it to an iPhone release but at least its in there :)

**Comment by MasterKale** [comment]
Thanks for reporting this, and for the follow-up! I'm going to close this out for now ✌️
