### ISSUE TITLE
https://webauthn.io/ not working on linux desktop

### ISSUE THREAD

**Issue by protono** [duo-labs/webauthn.io#126]
Steps:
- Open web site
- Advanced settings -> Reset settings
- Type a username, e.g. asasas
- Click the Register button

Expected to be able to create a token on the device.

- With Firefox on Android 14 it works just fine and I can choose out of 4 options for the security key (I select the screen lock option)
- With Firefox on Linux, I get an alert saying "The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission." even if under about:config `webauthn_enable_softtoken` is `true`
- With Chromium on Linux, I get a QR code which I read with my Android 14 mobile phone. There I see 'Use Passkey' but Google Lens freezes and I cannot go any further.

**Comment by MasterKale** [comment]
Hello @protono unfortunately these are issues with the OS and or browser. There's nothing to be done on webauthn.io itself to help solve these issues. The site does some basic feature detection on page load to try and understand if WebAuthn appears available for use. If the site thinks it can work then it lets you interact with it. After that it's on the OS and browser to support WebAuthn properly.
