### ISSUE TITLE
Registration using cross Platform authenticators fails for a few mobile phones.

### ISSUE THREAD

**Issue by ankushgarg1998** [duo-labs/webauthn.io#128]
Hi. I've tried to register cross-platform passkeys using a few different mobile phones. But a few of them are always failing.

I'm using the browser on my laptop.
Chromium Engine Version 122.0.6261.129
And I'm scanning the QR code on mobile to register passkey.

Mobiles that are not working:
1. OnePlus Nord - Android 12
2. Nothing Phone 1 - Android 13.

**DEVICE LOGS**
```
FIDOError[15:12:36] Failing make credential request due to status 0x27 (kCtap2ErrOperationDenied) from tunnel-F0D0D8D64EA8A10E
FIDODebug[15:12:36] -> (CTAP2 error code 0x27 (kCtap2ErrOperationDenied))
```

![Screenshot 2024-03-22 at 3 21 22 PM](https://github.com/duo-labs/webauthn.io/assets/22600172/849f0f3d-648e-4b43-8455-3fac0e2555b8)

I've tried to keep "Discoverable Credential" as "Discouraged" as well.

**Comment by MasterKale** [comment]
Hello @ankushgarg1998, unfortunately this is an issue between Android, Chrome, and possibly even your laptop's OS. I'm sorry to say but there's nothing that can really be done within webauthn.io to fix an issue like `kCtap2ErrOperationDenied` when attempting hybrid registration.

**Comment by ankushgarg1998** [comment]
Hi @MasterKale 
This has automatically started working now. I thought I'd let you know.
