### ISSUE TITLE
Wrong variable name in the sample code for parsing the attestationObject on webauthn.guide

### ISSUE THREAD

**Issue by bNobo** [duo-labs/webauthn.io#139]
Thank you very much for webauth.guide web site which is great and explains webauthn very well.

I've noticed a little mistake in this sample code:

```js
// note: a CBOR decoder library is needed here.
const decodedAttestationObj = CBOR.decode(
    credential.response.attestationObject);

console.log(decodedAttestationObject);
```

The variable is declared as decodedAttestationObj but `console.log` uses decodedAttestationObj**ect** which result to an "undefined variable" error.

I would have been happy to provide a pull request for this but I didn't found a repo for webauthn.guide, so I've created an issue here instead.

**Comment by MasterKale** [comment]
Hello @bNobo thanks for reporting this. A fix for this typo is now live on https://webauthn.guide 🚀
