### ISSUE TITLE
Safari

### ISSUE THREAD

**Issue by gingerbeardman** [duo-labs/webauthn.io#140]
Demo worked on iOS and macOS, but Safari is not mentioned on https://webauthn.io

**Comment by MasterKale** [comment]
Ah thanks @gingerbeardman I see what you mean! I definitely need to modernize the copy below the form:

> Welcome to webauthn.io! This site is designed by [Duo Labs](https://duo.com/labs) to test the new W3C Specification Web Authentication. WebAuthn is supported in **the Chrome, Firefox, and Edge browsers to different degrees**, but support for credential creation and assertion using a U2F Token, like those provided by Yubico and Feitian, is supported by all of them. The code for this demo can be found [here on GitHub](https://github.com/duo-labs/webauthn.io). To read more about WebAuthn and what it does, check out [webauthn.guide](https://webauthn.guide/) for an introduction.

**Comment by MasterKale** [comment]
Good news, I've modernized the site content to reflect the current wide availability of WebAuthn:

![Screenshot 2024-08-26 at 11 44 11 AM](https://github.com/user-attachments/assets/783f59f9-2885-4a1a-86f6-4b8fae86cf2e)

Thanks again @gingerbeardman 👏

**Comment by gingerbeardman** [comment]
Cheers!
