### ISSUE TITLE
Trying to access native fingerprint in Ubuntu 24.04

### ISSUE THREAD

**Issue by Muthu2602** [duo-labs/webauthn.io#145]
I am trying to access https://webauthn.io/ on my Ubuntu 24.04 with Firefox 129.0.2 (64-bit), but I am unable to use my native fingerprint reader.

**Comment by MasterKale** [comment]
Hello @Muthu2602 unfortunately this isn't going to be anything that can be addressed on webauthn.io directly. You're suffering from a fundamental lack of a platform authenticator in Linux space. There are two efforts underway to try and enable wider use of WebAuthn on Linux, check them out:

- https://github.com/iinuwa/linux-webauthn-platform-api
- https://github.com/AlfioEmanueleFresta/xdg-credentials-portal

But as far as I've known these are still a ways off from becoming a solution to your particular problem.
