### ISSUE TITLE
DOMException: Operation is not supported

### ISSUE THREAD

**Issue by sbrl** [duo-labs/webauthn.io#16]
I've seen quite a bit of noise recently about WebAuthn now being supported in Firefox for Android. I'm using Firefox for Android beta, but when I try the demo on webauthn.io, nothing happens. Using USB debugging, I get this in the console instead:

![image](https://user-images.githubusercontent.com/9929737/62547498-34464300-b85d-11e9-80f0-1afee7b98fbd.png)

What? I thought it was supported? I'm confused.

**Comment by nicksteele** [comment]
Sorry for the late reply, as of today in Firefox (stable) for Android, registration and login appear to be supported

**Comment by sbrl** [comment]
Ah, oops. I had a discussion elsewhere (can't remember precisely where though), and that wasn't the issue.

The problem was, @nicksteele, that you need Android v7+ (IIRC) in order to use NFC-based webauthn because of the backend features it makes use of - and I've got Android v6 on a Samsung S5 mini.

So this error is still occurring, but it is not a bug in webauthn.io.
