### ISSUE TITLE
"Windows Hello" and Firefox WebAuth?

### ISSUE THREAD

**Issue by horst789github** [duo-labs/webauthn.io#17]
who is familiar with "Windows Hello" and Firefox WebAuth? does not work with me somehow

![grafik](https://user-images.githubusercontent.com/35397597/62628696-1267c180-b92c-11e9-959e-09c3f71df1e0.png)

i can login with fingerprint on win10 (windows hello) but on this WebAuth featues the fingerprint dont work

**Comment by aseigler** [comment]
I just tested with this winver:

![image](https://user-images.githubusercontent.com/6605560/62638456-8180ee00-b90b-11e9-9c92-670d4ece207f.png)

And this Firefox build:

![image](https://user-images.githubusercontent.com/6605560/62638471-89d92900-b90b-11e9-9718-abe1162d582c.png)

Registration and logon worked perfectly with my fingerprint reader.

**Comment by horst789github** [comment]
nice thx for fast answer... i see you had "beta" from firefox and windows (insider program) anyone here can test with non beta branch?

i have:
![grafik](https://user-images.githubusercontent.com/35397597/62638868-a6428900-b93e-11e9-9c31-74e2edee80af.png)

![grafik](https://user-images.githubusercontent.com/35397597/62638907-b490a500-b93e-11e9-8bfc-248f94ca9e6b.png)

**Comment by aseigler** [comment]
Your Windows build will work fine, it's your Firefox build that is holding you back.

**Comment by horst789github** [comment]
ok thx, i will wait for new firefox stable release
