### ISSUE TITLE
Nothing happens with Safari 13 on macOS

### ISSUE THREAD

**Issue by slokhorst** [duo-labs/webauthn.io#20]
According to the [release notes](https://developer.apple.com/documentation/safari_release_notes/safari_13_release_notes), Safari 13 "Added support for FIDO2-compliant USB security keys with the Web Authentication standard in Safari on macOS."

However, when I try to use webauthn.io with Safari 13, and click the "Register" button, nothing happens. The console shows the following:
```
[Log] Fetching options for new credential (webauthn.js, line 80)
[Log] Credential Creation Options (webauthn.js, line 103)
[Log] {publicKey: Object} (webauthn.js, line 104)
```

Edit: after approximately one minute, the following shows:
```
[Info] NotAllowedError: Operation timed out. (webauthn.js, line 113)
```

Perhaps the same issue as in #16?

**Comment by grzuy** [comment]
Are you trying with USB Security Key or MacBook TouchID? I think Safari only supports USB for now.

**Comment by nicksteele** [comment]
Again, sorry for the late reply. This is an issue with Safari, as opposed to my library. I just tested MacOS Safari version 13.0.3 and it appears to work with USB-attached authenticators, however I don't see a prompt by the browser like Chrome and Firefox present.

**Comment by pro4tlzz** [comment]
@grzuy  do you have any idea when safari will support touchid for webauthn? I can't find it anyone online

**Comment by slokhorst** [comment]
@pro4tlzz likely somewhere in 2020. [WebKitGoalsfor2020](https://trac.webkit.org/wiki/WebKitGoalsfor2020) mentions:

> Authentication
> - WebAuthN external authenticators (NFC/USB) on iOS
> - Device-bound auth?

The first one is landing in iOS 13.3, the second one is probably referring to TPM (Secure Element/TouchID/FaceID).

**Comment by slokhorst** [comment]
It looks like the only implemented a proper UI just now. From the [Safari Technology Preview 97 release notes](https://webkit.org/blog/9672/release-notes-for-safari-technology-preview-97/):

> Added UI with instructions for authenticating with a security key while authenticating

It now looks like this:
<img width="522" alt="Screenshot 2019-12-18 at 22 01 00" src="https://user-images.githubusercontent.com/8083666/71123032-15c85f00-21e2-11ea-9d1f-47ec292b7ebf.png">

**Comment by pro4tlzz** [comment]
Thanks

**Comment by slokhorst** [comment]
It's coming in Safari 14!
> Added a Web Authentication platform authenticator using Face ID or Touch ID, depending on which capability is present.

https://developer.apple.com/documentation/safari-release-notes/safari-14-beta-release-notes
