### ISSUE TITLE
Authenticating over a phone (from a laptop)

### ISSUE THREAD

**Issue by KrishnaPG** [duo-labs/webauthn.io#21]
Trying to get a hold on the 2nd usecase listed in the spec ([here](https://www.w3.org/TR/webauthn-2/#sctn-usecase-authentication)), namely:
````
1.2.2. Authentication
    1.  On a laptop or desktop:

- User pairs their phone with the laptop or desktop via Bluetooth.
- 
- User navigates to example.com in a browser and initiates signing in.
- 
- User gets a message from the browser, "Please complete this action on your phone."

    2.  Next, on their phone:

- User sees a discrete prompt or notification, "Sign in to example.com."
- 
- User selects this prompt / notification.
- 
- User is shown a list of their example.com identities, e.g., "Sign in as Alice / Sign in as Bob."
- 
- User picks an identity, is prompted for an authorization gesture (PIN, biometric, etc.) and provides this.

    3.  Now, back on the laptop:

- Web page shows that the selected user is signed in, and navigates to the signed-in page.

````

Could not make this work with this demo. What options to choose in the UI (such as 'cross-platform', 'direct'/'indirect' etc.) to make this work?

The goal is to be able to start the login process on the laptop, use the fingerprint on phone, and complete the login back on laptop. How to make this work?

**Comment by nicksteele** [comment]
This is not yet supported by the WebAuthn standard. You would probably be interested [CaBLE](https://github.com/w3c/webauthn/pull/909) though, which would support this workflow. Additionally, [Krypton](https://github.com/kryptco/krypton-android) can support a flow like this, so you can see how they handle it as well. Hope these links help!
