### ISSUE TITLE
Authenticator Type 

### ISSUE THREAD

**Issue by BugsBountyHunter** [duo-labs/webauthn.io#25]
when I choose (platform) from Authenticator Type, not show **windows hello**  dialog and get me an error 
`time="2020-04-08T11:17:51Z" level=error msg="Error getting session securecookie: the value is not valid"`

**Comment by nicksteele** [comment]
What browser is this using? are you running this locally with or without HTTPS?

**Comment by DEV-A7med** [comment]
I'm using  Google Chrome and I run with The easiest way by using the image on Docker Hub.

**Comment by utezduyar** [comment]
I also see this problem. I just checked out the code today, built and ran it. I also use Chrome on http://127.0.0.1:9005/
Attestation type is none, authenticator type is unspecified. 
First time I click on "Register" button I see the same error message. Further clicks don't generate any error message. 
I see the user in the sqllite database under users table but nothing in the credentials table.

**Comment by MasterKale** [comment]
Closing this out as it's old and not relevant/fixed in v2
