### ISSUE TITLE
Username field is unclear

### ISSUE THREAD

**Issue by McIntireEvan** [duo-labs/webauthn.io#26]
The username field, [found here](https://github.com/duo-labs/webauthn.io/blob/master/templates/login.html#L12), has input type email, but placeholder text indicating a username.

This is unclear, as in Firefox and Chrome it indicates an error but still seems to accept the input (to the point of prompting for a security key, which I don't have).

Tested on Firefox 76.0.1 on Arch, where it highlights the field with a red outline, and Chrome 81.0.4044.92 where it does not, but shows an error if you hover.

**Comment by MasterKale** [comment]
The latest username input has `type="text"` and `autocomplete="username"` which should help clear up any confusion about the intended type of input data:

https://github.com/duo-labs/webauthn.io/blob/master/_app/homepage/templates/homepage/sections/webauthn_form.html#L9-L16
