### ISSUE TITLE
getAssertion does not use advanced settings

### ISSUE THREAD

**Issue by dschuermann** [duo-labs/webauthn.io#27]
In our tests, ``makeCredential`` seems to pick up the advanced settings correctly, i.e. selecting "user verification" as "discouraged" works.

But ``getAssertion`` seems not to use the advanced settings. At least "user verification" is not picked up. Instead, the Browser default is used.

I haven't verified this in your code.

https://webauthntest.azurewebsites.net/ does pick up "user verification" for getAssertion correctly.

**Comment by gtbuchanan** [comment]
I can confirm I experience a similar problem with "User Verification" set to "Required". "Login" is successful even on user agents that do not prompt for a PIN (Chrome for Android), which makes me think it's actually using "Preferred".

**Comment by MasterKale** [comment]
This was indeed an issue with the older version of the site. It's been addressed with the release of v2 of the site (#58).
