### ISSUE TITLE
Webauthn using biometric is not working on Safari 14

### ISSUE THREAD

**Issue by swapnil-salunke** [duo-labs/webauthn.io#31]
Updated to safari 14 on mac os Catalina, but don't get a biometric prompt during registration on my touch id enabled Macbook pro. Is the web app not updated to support safari yet or am I missing something?

![Screenshot 2020-09-17 at 11 33 33 AM](https://user-images.githubusercontent.com/59920365/93426914-8966dc00-f8da-11ea-87fc-5657c5cc7f22.jpg)
![Screenshot 2020-09-17 at 11 34 15 AM](https://user-images.githubusercontent.com/59920365/93426922-8c61cc80-f8da-11ea-8a44-8e9eedc97cc6.jpg)

**Comment by entrohpy** [comment]
Hi, I'm on Version 14.0.1 (16610.2.5) on macOS Big Sur and it seems to work for me:
<img width="720" alt="Screen Shot 2020-09-21 at 10 57 55" src="https://user-images.githubusercontent.com/12547595/93735177-b0cee900-fbf9-11ea-9880-1f1280d85ddc.png">
<img width="720" alt="Screen Shot 2020-09-21 at 10 58 03" src="https://user-images.githubusercontent.com/12547595/93735172-ac0a3500-fbf9-11ea-9075-17c78dfeac02.png">
<img width="720" alt="Screen Shot 2020-09-21 at 10 58 15" src="https://user-images.githubusercontent.com/12547595/93735167-a7458100-fbf9-11ea-93b4-77cd115eb6ee.png">
<img width="720" alt="Screen Shot 2020-09-21 at 10 58 21" src="https://user-images.githubusercontent.com/12547595/93735153-9c8aec00-fbf9-11ea-923b-66308c147469.png">

**Comment by swapnil-salunke** [comment]
So are you saying it would not work for safari on catalina? Even though Catalina now has Safari 14? And apple had promised Biometric support in Safari 14. Just want to give out accurate information for a client engagement.

**Comment by aseigler** [comment]
For now, you have to set the attestation type to none.  Apple has not released the specifications for their new custom attestation type.  See https://twitter.com/codekaiju/status/1306576215931789312

**Comment by swapnil-salunke** [comment]
Ok, point noted in case of iOS. How about latest update of safari on mac os catalina? Is anyone else also able to see the same issue as I posted? And do we have any timelines to check and maybe address this?

**Comment by Moumouls** [comment]
@swapnil-salunke  you are right Safari Version 14.0 on MacOS catalina do not prompt for fingerprint are password (only the key option)

**Comment by awsom82** [comment]
I think safari support only if FaceID or TouchID enabled devices.
So, no luck if you don't have a TochID keyboard and T2 chip. Maybe even locked to Apple M1.

**Comment by Moumouls** [comment]
Yes @awsom82  an Intel Macbook pro with touchID works, so Safari need at least one biometric system :)
