### ISSUE TITLE
Registering a credential with Safari 15.4 on Intel MacOS 12.3 fails with TouchID

### ISSUE THREAD

**Issue by frederikrothenberger** [duo-labs/webauthn.io#53]
Registering a new credential using TouchId, Safari 15.4 on an Intel MacBook Pro with MacOS 12.3 always fails with `NotAllowedError: This request has been cancelled by the user.`.

Using TouchID with Chrome works fine. Using a YubiKey works fine.

**Comment by MasterKale** [comment]
@frederikrothenberger Can you try this again with the latest version of the site (https://github.com/duo-labs/webauthn.io/pull/58) that's now live?

**Comment by frederikrothenberger** [comment]
@MasterKale: Unfortunately, the webauthn functionality is now broken completely when using Safari 15.6.1 (i.e. I could not find any combination of settings that allowed me to register successfully).

I only ever get the following error:

![Screenshot 2022-09-27 at 08 30 44](https://user-images.githubusercontent.com/94825501/192450155-91891ddb-2bf6-4e69-810b-d3762c734814.png)

There is no console output or any further information.

**Comment by MasterKale** [comment]
@frederikrothenberger I no longer have access to a machine running Safari 15.6.1. Is this still an issue for you? Maybe you can play around with the new **Discoverable Credential** option I added today to **Advanced Settings**, I wonder if Safari doesn't like it set to "preferred"? I'm grasping at straws right now, that's the best I've got.
