### ISSUE TITLE
webauthn.guide - outdated link

### ISSUE THREAD

**Issue by qd-qd** [duo-labs/webauthn.io#60]
Hi,
Just for information, the link [here](https://webauthn.guide/#The%20results%20are%20clear.) that redirects to Verizon's report is dead (in the paragraph "81% of all hacking-related breaches leverage stolen or weak passwords").
I wanted to update it but I didn't find the source of https://webauthn.guide/

The link should be https://www.verizon.com/business/resources/reports/2022/dbir/2022-data-breach-investigations-report-dbir.pdf

I can open a PR if you point me to the correct repository.

**Comment by MasterKale** [comment]
This is actually a pretty good question, I have to go digging to figure out where the repo for webauthn.guide resides 🤔

**Comment by MasterKale** [comment]
Hello @qd-qd, I managed to find this other link that I believe is the original document currently linked on https://webauthn.guide. And better yet it doesn't require you to submit any information to Verizon:

https://www.verizon.com/business/resources/reports/2017_dbir.pdf

I did a quick check and it has the same "81% of hacking-related breaches leveraged either stolen and/or weak passwords" fact in it, so unless you object I think I'll go with this link instead.

**Comment by qd-qd** [comment]
great, go ahead, thanks for digging 👌

**Comment by MasterKale** [comment]
The link on https://webauthn.guide has _finally_ been updated, thanks for your patience 🙇
