### ISSUE TITLE
Registering in Chrome Fails on MacOS Only

### ISSUE THREAD

**Issue by mesink** [duo-labs/webauthn.io#61]
When attempting to register on a mac with a new key, I get the prompt to set a pin. After entering the pin in both fields, the prompt disappears and nothing else happens. The registration appears to be aborted, and the pin is not set in the device. Console output shows:

`DOMexception: The operation either timed out or was not allowed. webauthn.js:120`

On a Windows device, after entering the pin, another prompt shows asking me to touch the authenticator, and the registration completes successfully.

**Comment by MasterKale** [comment]
@DanBujak Can you try this again with the latest version of the site (#58) that's now live?

**Comment by DanBujak** [comment]
I saw the new version, and unfortunately still see the same issue. It's not happening with all keys so I suspect it's something in the way certain devices are handling messages. Is there any debug functionality built into your server where I could see what messages are being sent/received to try to dig a bit deeper?

**Comment by MasterKale** [comment]
Alright, time for specifics then:

- What version of Chrome are you using?
- What version of macOS are you using?
- What type of security key are you using?
- Are you playing around with advanced settings at all? If so can you paste a link here please?

**Comment by mesink** [comment]
- Chrome V105.0.5195.125
- macOS 12.6
- I'm testing a number of keys and developing one
- I was just toggling between requiring and not requiring UV for registration but this feature does not seem to work as it did before.

All keys work fine on Windows 10 using Chrome. 3 of them (including the one I'm developing and have access to source for) aren't working on macOS. Tested on multiple versions of mac hardware OS and chrome.

**Comment by MasterKale** [comment]
Hello @mesink, can you try this scenario again, but open up a tab in chrome to `chrome://device-log/`, uncheck everything but "FIDO", and clear the box first. I'm wondering if you get anything that looks odd from the interaction between Chrome and security key.

**Comment by dlbk** [comment]
Hey, I did already resolve the issue by looking into the logs in chrome as you suggest. The RC was an incorrect value reported for the key agreement

**Comment by mesink** [comment]
Hey, I did already resolve the issue by looking into the logs in chrome as you suggest. The RC was an incorrect value reported for the key agreement
