### ISSUE TITLE
does not work with Samsung Galaxy A32 as authenticator

### ISSUE THREAD

**Issue by melkus** [duo-labs/webauthn.io#63]
It used to work before, maybe about a month ago, but suddenly stopped working.
It fails on Android side saying 'registration error' right after user complete the verification.

**Comment by MasterKale** [comment]
Hello @melkus, you might be suffering from Android's missing support for resident keys, but webauthn.io set the registration option to "preferred". Can you try going to https://webauthn.io with Discoverable Credential set to "discouraged" and register your phone again?

This URL will load the site with that option preset:

https://webauthn.io/?regRequireUserVerification=true&attestation=none&attachment=all&algES256=true&algRS256=true&discoverableCredential=discouraged&authRequireUserVerification=true
