### ISSUE TITLE
Can I add my library to the list?

### ISSUE THREAD

**Issue by dagnelies** [duo-labs/webauthn.io#70]
Hi!

I wrote following library in Typescript / JS:

https://github.com/passwordless-id/webauthn

Could this be added to the list of libraries?

**Comment by dagnelies** [comment]
Just submitted PR #71 ;)

**Comment by MasterKale** [comment]
I just merged #71, I'll perform my artisanal, hand-crafted deployment soon after which point you'll see it on the site!
