### ISSUE TITLE
server-side credentials are shown as passkeys

### ISSUE THREAD

**Issue by timcappalli** [duo-labs/webauthn.io#73]
When authenticating with a server-side credential (sometimes called a non-resident credential or U2F-style credential, the description text on the result page says `single-device non-discoverable passkey`.

Non-resident credentials are not passkeys.

I would suggest something like "single-device server-side credential" (although I don't think we really talk about single vs multi device for server side credentials).

**Comment by MasterKale** [comment]
I believe it was also proposed that these types of credentials be called, "multi-factor credentials"? That might be catchier than the technically accurate, "single-device server-side credential".

I'll play around with this and see what I land on.

**Comment by timcappalli** [comment]
These test sites are for a technical audience, so verbose / accuracy is more important than catchy IMO.
