### ISSUE TITLE
Update to "device-bound passkey"

### ISSUE THREAD

**Issue by timcappalli** [duo-labs/webauthn.io#87]
The new name for a `single-device passkey` is `device-bound passkey`.  Hopefully that is the last name change :)

**Comment by MasterKale** [comment]
Thanks for reporting this @timcappalli, I'll address this before too long ✌️

**Comment by MasterKale** [comment]
This change is now live 🎉 

![Screenshot 2023-05-09 at 5 16 16 PM](https://github.com/duo-labs/webauthn.io/assets/5166470/0eb20f6b-0f1b-4bde-9f0c-36501ef3c749)
