### ISSUE TITLE
Dump requests and responses to console

### ISSUE THREAD

**Issue by timcappalli** [duo-labs/webauthn.io#93]
It would be helpful to see the raw request and response objects and server responses in console.

(If you don't want to enable it all the time, maybe it can be triggered via a URL parameter: debug=true, verbose=true, console=true, etc)

Something like this:

![image](https://user-images.githubusercontent.com/6476604/236889446-e3cb4fe5-c431-417f-b37a-68fb829aa8f1.png)

**Comment by MasterKale** [comment]
This has been fixed with #95 and is now live :v:
